### ISSUE TITLE
create_dictionary.py needs support for special chcracters

### ISSUE THREAD

**Issue by patrick-yeadon** [patrick-yeadon/code-jam-4#5]
Also should have even probabilities to pick a word with each latter of the alphabet, that way the user doesn't have to wait a long time for the letter 'z' to show up, for example.

**Comment by jeepitou** [comment]
I was thinking the program would iterate throught its dictionary and pick the word that eliminate the most possibility. For example if the only letter possibilities are [a, e, h, t, l, w, p, z, b], it would ask something like "Is your letter in 'zebra'. 
Were you thinking of just picking random words in the list ? This could be crazy long xD

As for the special characters, ,I guess we are only supporting english langage, so it's a bit easier.
